// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ETerminal.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Et_TerminalPacketType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case keepAlive = 0
  case terminalBuffer = 1
  case terminalInfo = 2
  case portForwardDestinationRequest = 5
  case portForwardDestinationResponse = 6
  case portForwardData = 7
  case terminalUserInfo = 8
  case terminalInit = 9
  case jumphostInit = 10

  public init() {
    self = .keepAlive
  }

}

public nonisolated struct Et_TerminalBuffer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var buffer: Data {
    get {_buffer ?? Data()}
    set {_buffer = newValue}
  }
  /// Returns true if `buffer` has been explicitly set.
  public var hasBuffer: Bool {self._buffer != nil}
  /// Clears the value of `buffer`. Subsequent reads from it will return its default value.
  public mutating func clearBuffer() {self._buffer = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _buffer: Data? = nil
}

public nonisolated struct Et_TerminalInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {_id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var row: Int32 {
    get {_row ?? 0}
    set {_row = newValue}
  }
  /// Returns true if `row` has been explicitly set.
  public var hasRow: Bool {self._row != nil}
  /// Clears the value of `row`. Subsequent reads from it will return its default value.
  public mutating func clearRow() {self._row = nil}

  public var column: Int32 {
    get {_column ?? 0}
    set {_column = newValue}
  }
  /// Returns true if `column` has been explicitly set.
  public var hasColumn: Bool {self._column != nil}
  /// Clears the value of `column`. Subsequent reads from it will return its default value.
  public mutating func clearColumn() {self._column = nil}

  public var width: Int32 {
    get {_width ?? 0}
    set {_width = newValue}
  }
  /// Returns true if `width` has been explicitly set.
  public var hasWidth: Bool {self._width != nil}
  /// Clears the value of `width`. Subsequent reads from it will return its default value.
  public mutating func clearWidth() {self._width = nil}

  public var height: Int32 {
    get {_height ?? 0}
    set {_height = newValue}
  }
  /// Returns true if `height` has been explicitly set.
  public var hasHeight: Bool {self._height != nil}
  /// Clears the value of `height`. Subsequent reads from it will return its default value.
  public mutating func clearHeight() {self._height = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: String? = nil
  fileprivate var _row: Int32? = nil
  fileprivate var _column: Int32? = nil
  fileprivate var _width: Int32? = nil
  fileprivate var _height: Int32? = nil
}

public nonisolated struct Et_PortForwardSourceRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var source: Et_SocketEndpoint {
    get {_source ?? Et_SocketEndpoint()}
    set {_source = newValue}
  }
  /// Returns true if `source` has been explicitly set.
  public var hasSource: Bool {self._source != nil}
  /// Clears the value of `source`. Subsequent reads from it will return its default value.
  public mutating func clearSource() {self._source = nil}

  public var destination: Et_SocketEndpoint {
    get {_destination ?? Et_SocketEndpoint()}
    set {_destination = newValue}
  }
  /// Returns true if `destination` has been explicitly set.
  public var hasDestination: Bool {self._destination != nil}
  /// Clears the value of `destination`. Subsequent reads from it will return its default value.
  public mutating func clearDestination() {self._destination = nil}

  public var environmentvariable: String {
    get {_environmentvariable ?? String()}
    set {_environmentvariable = newValue}
  }
  /// Returns true if `environmentvariable` has been explicitly set.
  public var hasEnvironmentvariable: Bool {self._environmentvariable != nil}
  /// Clears the value of `environmentvariable`. Subsequent reads from it will return its default value.
  public mutating func clearEnvironmentvariable() {self._environmentvariable = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _source: Et_SocketEndpoint? = nil
  fileprivate var _destination: Et_SocketEndpoint? = nil
  fileprivate var _environmentvariable: String? = nil
}

public nonisolated struct Et_PortForwardSourceResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var error: String {
    get {_error ?? String()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: String? = nil
}

public nonisolated struct Et_PortForwardDestinationRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var destination: Et_SocketEndpoint {
    get {_destination ?? Et_SocketEndpoint()}
    set {_destination = newValue}
  }
  /// Returns true if `destination` has been explicitly set.
  public var hasDestination: Bool {self._destination != nil}
  /// Clears the value of `destination`. Subsequent reads from it will return its default value.
  public mutating func clearDestination() {self._destination = nil}

  public var fd: Int32 {
    get {_fd ?? 0}
    set {_fd = newValue}
  }
  /// Returns true if `fd` has been explicitly set.
  public var hasFd: Bool {self._fd != nil}
  /// Clears the value of `fd`. Subsequent reads from it will return its default value.
  public mutating func clearFd() {self._fd = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _destination: Et_SocketEndpoint? = nil
  fileprivate var _fd: Int32? = nil
}

public nonisolated struct Et_PortForwardDestinationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var clientfd: Int32 {
    get {_clientfd ?? 0}
    set {_clientfd = newValue}
  }
  /// Returns true if `clientfd` has been explicitly set.
  public var hasClientfd: Bool {self._clientfd != nil}
  /// Clears the value of `clientfd`. Subsequent reads from it will return its default value.
  public mutating func clearClientfd() {self._clientfd = nil}

  public var socketid: Int32 {
    get {_socketid ?? 0}
    set {_socketid = newValue}
  }
  /// Returns true if `socketid` has been explicitly set.
  public var hasSocketid: Bool {self._socketid != nil}
  /// Clears the value of `socketid`. Subsequent reads from it will return its default value.
  public mutating func clearSocketid() {self._socketid = nil}

  public var error: String {
    get {_error ?? String()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _clientfd: Int32? = nil
  fileprivate var _socketid: Int32? = nil
  fileprivate var _error: String? = nil
}

public nonisolated struct Et_PortForwardData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sourcetodestination: Bool {
    get {_sourcetodestination ?? false}
    set {_sourcetodestination = newValue}
  }
  /// Returns true if `sourcetodestination` has been explicitly set.
  public var hasSourcetodestination: Bool {self._sourcetodestination != nil}
  /// Clears the value of `sourcetodestination`. Subsequent reads from it will return its default value.
  public mutating func clearSourcetodestination() {self._sourcetodestination = nil}

  public var socketid: Int32 {
    get {_socketid ?? 0}
    set {_socketid = newValue}
  }
  /// Returns true if `socketid` has been explicitly set.
  public var hasSocketid: Bool {self._socketid != nil}
  /// Clears the value of `socketid`. Subsequent reads from it will return its default value.
  public mutating func clearSocketid() {self._socketid = nil}

  public var buffer: Data {
    get {_buffer ?? Data()}
    set {_buffer = newValue}
  }
  /// Returns true if `buffer` has been explicitly set.
  public var hasBuffer: Bool {self._buffer != nil}
  /// Clears the value of `buffer`. Subsequent reads from it will return its default value.
  public mutating func clearBuffer() {self._buffer = nil}

  public var error: String {
    get {_error ?? String()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var closed: Bool {
    get {_closed ?? false}
    set {_closed = newValue}
  }
  /// Returns true if `closed` has been explicitly set.
  public var hasClosed: Bool {self._closed != nil}
  /// Clears the value of `closed`. Subsequent reads from it will return its default value.
  public mutating func clearClosed() {self._closed = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _sourcetodestination: Bool? = nil
  fileprivate var _socketid: Int32? = nil
  fileprivate var _buffer: Data? = nil
  fileprivate var _error: String? = nil
  fileprivate var _closed: Bool? = nil
}

public nonisolated struct Et_InitialPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var jumphost: Bool {
    get {_jumphost ?? false}
    set {_jumphost = newValue}
  }
  /// Returns true if `jumphost` has been explicitly set.
  public var hasJumphost: Bool {self._jumphost != nil}
  /// Clears the value of `jumphost`. Subsequent reads from it will return its default value.
  public mutating func clearJumphost() {self._jumphost = nil}

  public var reversetunnels: [Et_PortForwardSourceRequest] = []

  public var environmentvariables: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _jumphost: Bool? = nil
}

public nonisolated struct Et_InitialResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var error: String {
    get {_error ?? String()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: String? = nil
}

public nonisolated struct Et_ConfigParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var vlevel: Int32 {
    get {_vlevel ?? 0}
    set {_vlevel = newValue}
  }
  /// Returns true if `vlevel` has been explicitly set.
  public var hasVlevel: Bool {self._vlevel != nil}
  /// Clears the value of `vlevel`. Subsequent reads from it will return its default value.
  public mutating func clearVlevel() {self._vlevel = nil}

  public var minloglevel: Int32 {
    get {_minloglevel ?? 0}
    set {_minloglevel = newValue}
  }
  /// Returns true if `minloglevel` has been explicitly set.
  public var hasMinloglevel: Bool {self._minloglevel != nil}
  /// Clears the value of `minloglevel`. Subsequent reads from it will return its default value.
  public mutating func clearMinloglevel() {self._minloglevel = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _vlevel: Int32? = nil
  fileprivate var _minloglevel: Int32? = nil
}

public nonisolated struct Et_TermInit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var environmentnames: [String] = []

  public var environmentvalues: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Et_TerminalUserInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {_id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var passkey: String {
    get {_passkey ?? String()}
    set {_passkey = newValue}
  }
  /// Returns true if `passkey` has been explicitly set.
  public var hasPasskey: Bool {self._passkey != nil}
  /// Clears the value of `passkey`. Subsequent reads from it will return its default value.
  public mutating func clearPasskey() {self._passkey = nil}

  public var uid: Int64 {
    get {_uid ?? 0}
    set {_uid = newValue}
  }
  /// Returns true if `uid` has been explicitly set.
  public var hasUid: Bool {self._uid != nil}
  /// Clears the value of `uid`. Subsequent reads from it will return its default value.
  public mutating func clearUid() {self._uid = nil}

  public var gid: Int64 {
    get {_gid ?? 0}
    set {_gid = newValue}
  }
  /// Returns true if `gid` has been explicitly set.
  public var hasGid: Bool {self._gid != nil}
  /// Clears the value of `gid`. Subsequent reads from it will return its default value.
  public mutating func clearGid() {self._gid = nil}

  public var fd: Int64 {
    get {_fd ?? 0}
    set {_fd = newValue}
  }
  /// Returns true if `fd` has been explicitly set.
  public var hasFd: Bool {self._fd != nil}
  /// Clears the value of `fd`. Subsequent reads from it will return its default value.
  public mutating func clearFd() {self._fd = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: String? = nil
  fileprivate var _passkey: String? = nil
  fileprivate var _uid: Int64? = nil
  fileprivate var _gid: Int64? = nil
  fileprivate var _fd: Int64? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "et"

nonisolated extension Et_TerminalPacketType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0KEEP_ALIVE\0\u{1}TERMINAL_BUFFER\0\u{1}TERMINAL_INFO\0\u{2}\u{3}PORT_FORWARD_DESTINATION_REQUEST\0\u{1}PORT_FORWARD_DESTINATION_RESPONSE\0\u{1}PORT_FORWARD_DATA\0\u{1}TERMINAL_USER_INFO\0\u{1}TERMINAL_INIT\0\u{1}JUMPHOST_INIT\0")
}

nonisolated extension Et_TerminalBuffer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TerminalBuffer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}buffer\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._buffer) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._buffer {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_TerminalBuffer, rhs: Et_TerminalBuffer) -> Bool {
    if lhs._buffer != rhs._buffer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_TerminalInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TerminalInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}row\0\u{1}column\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._row) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._column) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._width) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._row {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._column {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._width {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._height {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_TerminalInfo, rhs: Et_TerminalInfo) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._row != rhs._row {return false}
    if lhs._column != rhs._column {return false}
    if lhs._width != rhs._width {return false}
    if lhs._height != rhs._height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_PortForwardSourceRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PortForwardSourceRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}source\0\u{1}destination\0\u{1}environmentvariable\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._source) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._destination) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._environmentvariable) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._source {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._destination {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._environmentvariable {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_PortForwardSourceRequest, rhs: Et_PortForwardSourceRequest) -> Bool {
    if lhs._source != rhs._source {return false}
    if lhs._destination != rhs._destination {return false}
    if lhs._environmentvariable != rhs._environmentvariable {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_PortForwardSourceResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PortForwardSourceResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._error {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_PortForwardSourceResponse, rhs: Et_PortForwardSourceResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_PortForwardDestinationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PortForwardDestinationRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}destination\0\u{1}fd\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._destination) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._fd) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._destination {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._fd {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_PortForwardDestinationRequest, rhs: Et_PortForwardDestinationRequest) -> Bool {
    if lhs._destination != rhs._destination {return false}
    if lhs._fd != rhs._fd {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_PortForwardDestinationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PortForwardDestinationResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}clientfd\0\u{1}socketid\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._clientfd) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._socketid) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._clientfd {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._socketid {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._error {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_PortForwardDestinationResponse, rhs: Et_PortForwardDestinationResponse) -> Bool {
    if lhs._clientfd != rhs._clientfd {return false}
    if lhs._socketid != rhs._socketid {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_PortForwardData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PortForwardData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sourcetodestination\0\u{1}socketid\0\u{1}buffer\0\u{1}error\0\u{1}closed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._sourcetodestination) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._socketid) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._buffer) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._error) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._closed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._sourcetodestination {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._socketid {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._buffer {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._error {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._closed {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_PortForwardData, rhs: Et_PortForwardData) -> Bool {
    if lhs._sourcetodestination != rhs._sourcetodestination {return false}
    if lhs._socketid != rhs._socketid {return false}
    if lhs._buffer != rhs._buffer {return false}
    if lhs._error != rhs._error {return false}
    if lhs._closed != rhs._closed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_InitialPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InitialPayload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}jumphost\0\u{1}reversetunnels\0\u{1}environmentvariables\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._jumphost) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.reversetunnels) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.environmentvariables) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._jumphost {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    if !self.reversetunnels.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.reversetunnels, fieldNumber: 2)
    }
    if !self.environmentvariables.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.environmentvariables, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_InitialPayload, rhs: Et_InitialPayload) -> Bool {
    if lhs._jumphost != rhs._jumphost {return false}
    if lhs.reversetunnels != rhs.reversetunnels {return false}
    if lhs.environmentvariables != rhs.environmentvariables {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_InitialResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InitialResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._error {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_InitialResponse, rhs: Et_InitialResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_ConfigParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConfigParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}vlevel\0\u{1}minloglevel\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._vlevel) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._minloglevel) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._vlevel {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._minloglevel {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_ConfigParams, rhs: Et_ConfigParams) -> Bool {
    if lhs._vlevel != rhs._vlevel {return false}
    if lhs._minloglevel != rhs._minloglevel {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_TermInit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TermInit"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}environmentnames\0\u{1}environmentvalues\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.environmentnames) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.environmentvalues) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.environmentnames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.environmentnames, fieldNumber: 1)
    }
    if !self.environmentvalues.isEmpty {
      try visitor.visitRepeatedStringField(value: self.environmentvalues, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_TermInit, rhs: Et_TermInit) -> Bool {
    if lhs.environmentnames != rhs.environmentnames {return false}
    if lhs.environmentvalues != rhs.environmentvalues {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Et_TerminalUserInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TerminalUserInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}passkey\0\u{1}uid\0\u{1}gid\0\u{1}fd\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._passkey) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self._uid) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self._gid) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self._fd) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._passkey {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._uid {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._gid {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._fd {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Et_TerminalUserInfo, rhs: Et_TerminalUserInfo) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._passkey != rhs._passkey {return false}
    if lhs._uid != rhs._uid {return false}
    if lhs._gid != rhs._gid {return false}
    if lhs._fd != rhs._fd {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
